### ISSUE TITLE
Missing projects in the configuration

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/dashboard#26]
Found a couple of active projects missing in the configuration.
For example, `jekyll-seo-tag`, `jemoji`..
Perhaps, more..?

**Comment by ashmaroli** [comment]
Did a bit of investigation..
Just in case you didn't know already, the reason is because the API is only returning 30 repositories per call. The remaining repos are in the *next-page* of the paginated response.

However, I don't see a way to pass that parameter via `go-github`..

**Comment by parkr** [comment]
Of course! I suspected something like that was the case. There should be an example of pagination somewhere. Usually it's like `req.Page = resp.NextPage` in an endless `for` loop.
