### ISSUE TITLE
Entry for `jekyll/directory` shows unrelated gem info

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/dashboard#29]
`jekyll/directory` is not a Ruby project nor a Jekyll theme.
Therefore, it shouldn't have gem metadata:

![dashboard jekyllrb com](https://user-images.githubusercontent.com/12479464/140404913-450d645c-a0a5-4ad3-8e6f-f06f41eb3e00.png)

**Comment by parkr** [comment]
Ooops! I wonder if removing the gem name from this project would fix this.

**Comment by parkr** [comment]
ac5a25a
