### ISSUE TITLE
Sort rows by desired column at client-side

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/dashboard#30]
For example, `unreleased_commits` is the one data cell that is of most importance when one would like to think about cutting a new release. At another time, the total number of issue tickets open is most important to give clues to which repository needs priority for triaging, etc.

Since the dashboard data is rendered as a table, it would be helpful to be able to sort the table by desired column **client-side**.

**Comment by parkr** [comment]
Sounds good! 👍 I'd probably hesitate to add a big JS library for this in lieu of some custom code if it's not too big a lift. Essentially you'd want a click listener to the top row cells to sorts the other rows by the value. Using JS's built-in comparison operator would probably work well here. If you find a tiny JS library we could give that a try too.
